# Generated by Django 4.0.1 on 2022-01-22 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='board',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='letters',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='player1_letters',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='player2_letters',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('13f9200e-19b3-4ad5-8826-02ad5f88578e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
