# Generated by Django 4.0.1 on 2022-01-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0006_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='board',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='letters',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='player1_letters',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='player2_letters',
            field=models.TextField(default=''),
        ),
    ]
