# Generated by Django 4.0.1 on 2022-01-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0007_room_in_progress_alter_room_board_alter_room_letters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player1_turn',
            field=models.BooleanField(default=True),
        ),
    ]
