# Generated by Django 4.0.1 on 2022-01-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0008_room_player1_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player1_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='player2_points',
            field=models.IntegerField(default=0),
        ),
    ]
