# Generated by Django 4.0.1 on 2022-01-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0009_room_player1_points_room_player2_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='pass_counter',
            field=models.IntegerField(default=0),
        ),
    ]
